// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwxebnepagdpiazbvsly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3eGVibmVwYWdkcGlhemJ2c2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjY2ODEsImV4cCI6MjA2NTU0MjY4MX0.VuvFlII2r7VCgCCgv0szIpu6HWKQMXO17h71pboM68U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);